### PR TITLE
move glide files to the top directory

### LINKED ISSUE #615: [WIP]Move glide.yaml and glide.lock to the top directory
This could be helpful that we can run `glide install -v` directly under the top-level directory, then the `vendor` directory is not created inside `go` folder which could be annoying.

### PR DESCRIPTION
**Pull request by m3ngyang**
fix #615

### CODE REVIEW

**Comment by typhoonzero** [comment]
@Yancey1989 how to build and test go code under `doc` folder?

**Comment by m3ngyang** [comment]
@typhoonzero problem solved, but we cannot get `gonum.org/v1/plot` directly.
We need to set a mirror for the repo when using `glide install` locally.
`glide mirror set https://gonum.org/v1/plot https://github.com/gonum/plot`

**Comment by typhoonzero** [comment]
> but we cannot get gonum.org/v1/plot directly.

This may not be a problem for Go developers in China.

**Comment by m3ngyang** [comment]
This is not caused by the internet connection. There is a discussion [here](https://github.com/gonum/gonum/issues/260) and I use glide mirror to walk around the problem.

**Comment by typhoonzero** [comment]
I see, thanks!

**Pull request merged**
