### PR TITLE
Change to use the updated deepcopy generation program

### PR DESCRIPTION
**Pull request by wangkuiyi**
Fix https://github.com/PaddlePaddle/cloud/issues/585

### CODE REVIEW

**Comment by wangkuiyi** [comment]
It is a little strange here that the CI passes but my local build doesn't:

```
glide install --strip-vendor
go test $(glide nv)
?   	github.com/PaddlePaddle/cloud/go/cfs	[no test files]
# github.com/PaddlePaddle/cloud/go/pkg/apis/paddlepaddle/v1alpha1
pkg/apis/paddlepaddle/v1alpha1/register.go:25:16: cannot use TrainingJob literal (type *TrainingJob) as type runtime.Object in argument to scheme.AddKnownTypes:
	*TrainingJob does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/paddlepaddle/v1alpha1/register.go:26:20: cannot use TrainingJobList literal (type *TrainingJobList) as type runtime.Object in argument to scheme.AddKnownTypes:
	*TrainingJobList does not implement runtime.Object (missing DeepCopyObject method)
```

**Comment by typhoonzero** [comment]
`go/edl/resource/deepcopy_gen.sh` seems not used any more. Newly checked in code by @m3ngyang  try to define CRD resources, need to run `bash ./vendor/k8s.io/code-generator/generate-groups.sh "deepcopy,client,informer,lister" github.com/PaddlePaddle/cloud/go/pkg/client github.com/PaddlePaddle/cloud/go/pkg/apis paddlepaddle:v1alpha1` before running `go test`, see: https://github.com/PaddlePaddle/cloud/blob/develop/.travis.yml#L16

**Comment by typhoonzero** [comment]
And, develop branch is going on to CRD, if we want to build TPR version, we have to checkout the previous release tag. Only CRD need to generate DeepCopy codes.

**Comment by wangkuiyi** [comment]
Does this mean that what this PR should do is to remove `deepcopy_gen.sh` and `zz_generated.deepcopy.go`?

**Comment by typhoonzero** [comment]
Yes, we can remove these files.

**Comment by typhoonzero** [comment]
Sorry, seems these two files can not be removed for now, because we have already updated the Kubernetes API dependency to 1.8, the resource defination must require generated DeepCopy file.

I'll try to go over the code again tomorrow to fix this problem.

**Comment by m3ngyang** [comment]
As discussed under pr #565 , the problem of deepcopy generation of crd  will be solved ASAP.

**Comment by wangkuiyi** [comment]
Thanks to @m3ngyang . I am closing this PR.

**Pull request closed without merging**
